style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/bdarcus/csl-next
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - refactor
  commit_groups:
    group_by: Type
    sort_by: Title
    title_maps:
      feat: Added
      fix: Fixed
      refactor: Changed
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
