# update json schemas when tagged
name: Update schemas
on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Update schemas
        uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: v1.x
      - run: deno task schemas

